name: Deploy Frontend to S3 (DEV)

on:
  push:
    branches: ["dev"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync frontend to S3 bucket
        run: aws s3 sync ./frontend s3://dev.jijilthomas.online --delete

      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id E2ON4IC7XBS7MR --paths "/*"
