name: Deploy Frontend to S3 (PROD)

on:
  push:
    branches: ["prod"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform init PROD
        working-directory: infra-prod
        run: terraform init -reconfigure

      - name: Terraform apply PROD
        working-directory: infra-prod
        run: terraform apply -auto-approve -var-file=prod.tfvars

      - name: Replace API URL (PROD)
        run: sed -i 's|{{API_URL}}|https://q6lq9z9lj7.execute-api.ap-south-1.amazonaws.com/prod/|g' frontend/index.html


      - name: Sync frontend to S3 bucket (PROD)
        run: aws s3 sync ./frontend s3://portfolio.jijilthomas.online --delete

      - name: Get CloudFront ID (PROD)
        id: get_cf
        working-directory: infra-prod
        run: echo "CF_ID=$(terraform output -raw cloudfront_distribution_id)" >> "$GITHUB_ENV"

      - name: Invalidate CloudFront (PROD)
        run: aws cloudfront create-invalidation --distribution-id "${{ env.CF_ID }}" --paths "/*"
